version: '3.7'

services:
  user_db:
    build:
      context: .
      dockerfile: ./db.dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: userdatabase
      POSTGRES_USER: argadev
      POSTGRES_PASSWORD: 123456